services:

  envoy:
    image: envoyproxy/envoy:v1.32-latest
    container_name: envoy
    ports:
      - "9080:9080"
      - "9901:9901"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - logs:/tmp
    depends_on:
      - vector
    user: root

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      - logs:/var/log:ro
    environment:
      - REDIS_HOST=REDIS_HOST
      - REDIS_PORT=6379

volumes:
  logs:
